// Supabase client configuration variables
window.SUPABASE_URL = "https://fkheqnnazjsgxebziwjn.supabase.co";
window.SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZraGVxbm5hempzZ3hlYnppd2puIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODIyMTYwODIsImV4cCI6MjA5Nzc5MjA4Mn0.1crSgKS1A3-6ZIzx0gRiV1r-ZShlg_Z0LjIo24rvOcY";
